name: ${CHATTER_ROLE:-talker}-ros2router

services:
  chatter:
    build: .
    command: ros2 run demo_nodes_cpp ${CHATTER_ROLE:-talker}

  ros2router:
    image: husarnet/ros2router:1.9.2
    network_mode: service:husarnet
    depends_on: 
      husarnet: { condition: service_healthy } # husarnet service is healthy if all hosts listed in WAIT_HOSTNAMES are reachable
    volumes:
      - ./filter.yaml:/filter.yaml
    environment:
      - PARTICIPANTS=husarnet,lan
      - ROS_DISCOVERY_SERVER=;;;talker-host

  husarnet:
    image: husarnet/husarnet:2.0.180
    volumes:
      - /var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=${CHATTER_ROLE:-talker}-host
      - JOINCODE
      - HUSARNET_DEBUG=1
      - WAIT_HOSTNAMES=talker-host