name: discovery-server

services:
  ds:
    image: ros:jazzy-ros-core
    network_mode: service:husarnet
    command: fastdds discovery -i 0 -l husarnet-local -p 11811

  husarnet:
    image: husarnet/husarnet:2.0.180
    volumes:
      - /var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=ds-host
      - JOINCODE
      - HUSARNET_DEBUG=1
