name: localhost-ros2router

services:
  ros2router:
    image: husarnet/ros2router:1.9.2
    restart: always
    network_mode: host
    ipc: host
    volumes:
      - ./filter.yaml:/filter.yaml
    environment:
      - PARTICIPANTS=husarnet,lo
      - ROS_DISCOVERY_SERVER=;;;talker-host
      - USER
